### PR TITLE
A few minor updates

### PR DESCRIPTION
**Pull request by joshand**
* Add set_help_message method to allow customization of help message banner
* Remove case sensitivity in commands
* Add sorting of commands when showing help
* Add unit tests / fix flake formatting issues
* Update to allow bot to handle more than messages:created; tested with memberships:all

Details around the last one:
I was in need of a bot that could monitor memberships data, so I extended this one to do that.

With the changes in the PR, the default behavior is still in tact. However, here is an example of how you would monitor membership changes:

In your main code, when you create an instance of the bot, add the "webhook_resource" and "webhook_event" parameters:
```
bot = TeamsBot(bot_app_name, teams_bot_token=spark_token,
               teams_bot_url=bot_url, teams_bot_email=bot_email, debug=True,
               webhook_resource="memberships", webhook_event="all")
```

Then, add a new command for the resource you want to monitor:
`bot.add_command('memberships', '*', check_memberships)
`

Finally, add a function to handle that command. For example, I needed the bot (which is assigned to the room as a moderator) to be able to remove anyone from a room who is not in a set of whitelisted domains (i.e., to ensure that a room stays "internal-only"). This function has an additional parameter (api in my example), which is used to directly access the WebexTeamsSDK object.
```
def check_memberships(api, incoming_msg):
    wl_dom = os.getenv("WHITELIST_DOMAINS")
    if wl_dom.find("[") < 0:
        wl_dom = '["' + wl_dom + '"]'
        wl_dom = wl_dom.replace(",", '","')

    if wl_dom and incoming_msg["event"] != "deleted":
        pemail = incoming_msg["data"]["personEmail"]
        pid = incoming_msg["data"]["personId"]
        pdom = pemail.split("@")[1]
        plist = json.loads(wl_dom)
        print(pemail, pdom, plist)
        if pdom in plist or pemail == bot_email:
            # membership check succeeded
            return ""
        else:
            # membership check failed
            print("membership failed. deleting " + incoming_msg["data"]["id"])
            api.memberships.delete(incoming_msg["data"]["id"])
            api.messages.create(toPersonId=pid, markdown="You were automatically removed from the space because "
                                     "it is restricted to internal employees.")
            return "'" + pemail + "' was automatically removed from this space; it is restricted to only internal users."

    return ""
```

### CODE REVIEW

**Comment by joshand** [comment]
I needed the bot to be able to handle cards (attachments) as well, so I made another enhancement. Now you can instanciate the bot using:
```
bot = TeamsBot(bot_app_name, teams_bot_token=spark_token,
               teams_bot_url=bot_url, teams_bot_email=bot_email, default_action="help", debug=True,
               webhook_resource_event=[{"resource": "messages", "event": "created"},
                                       {"resource": "attachmentActions", "event": "created"}])
```

Add a new command like this:
```
bot.add_command('attachmentActions', '*', handle_cards)
```

Then you can retrieve card actions like this:
```
def handle_cards(api, incoming_msg):
    m = get_attachment_actions(incoming_msg["data"]["id"])
    return m["inputs"]

def get_attachment_actions(attachmentid):
    headers = {
        'content-type': 'application/json; charset=utf-8',
        'authorization': 'Bearer ' + teams_token
    }

    url = 'https://api.ciscospark.com/v1/attachment/actions/' + attachmentid
    response = requests.get(url, headers=headers)
    return response.json()
```

**Comment by joshand** [comment]
Just a note - this does change the naming format of webhooks in Webex Teams, so if there is any downstream code that is leveraging the actual webhook name, it is changing. The change is to more easily support multiple webhooks for various events / resources.

**Comment by joshand** [comment]
Also added a new function "add_new_url". This function will add a new entry to Flask so that you can use the same bot interface to handle other things... for example, I'm using this to allow the bot to also receive webhooks from Meraki Dashboard...

```
bot.add_new_url("/meraki", "meraki", meraki_webhooks)
```

Now, if you GET, POST, or PUT to your url/meraki, the bot will call the meraki_webhooks function with any data that is provided.

**Comment by hpreston** [comment]
@joshand thanks for teh PR and the great enhancements.  I'm going to merge this in, but when you get a chance I'd love an update the the README file that includes the additional options.

**Pull request merged**
